# Generated by Django 5.2.7 on 2025-11-27 20:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingWorkflowExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout'), ('RUNNING', 'Running')], db_index=True, default='RUNNING', max_length=20)),
                ('execution_duration', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('currencies', models.JSONField(help_text="List of currencies analyzed (e.g., ['BTC', 'ETH'])")),
                ('balance_info', models.JSONField(help_text='Complete balance snapshot including total, available, and unrealized PnL')),
                ('market_data', models.JSONField(help_text='Market data for each currency including price, indicators, OI, and funding rate')),
                ('open_positions', models.JSONField(default=list, help_text='All open positions with associated orders and risk metrics')),
                ('daily_pnl', models.JSONField(help_text='Daily performance metrics: PnL, trade count, win rate')),
                ('agent_response', models.TextField(blank=True, help_text='Full AI agent analysis and decision rationale')),
                ('agent_actions_taken', models.JSONField(blank=True, default=list, help_text='Structured list of actions taken by the agent')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed')),
                ('error_traceback', models.TextField(blank=True, help_text='Full stack trace for debugging')),
            ],
            options={
                'verbose_name': 'Trading Workflow Execution',
                'verbose_name_plural': 'Trading Workflow Executions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='tradings_tr_created_bb3761_idx')],
            },
        ),
    ]
