# Generated by Django 5.2.7 on 2025-11-27 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tradings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingworkflowexecution",
            name="agent_streaming_output",
            field=models.TextField(
                blank=True,
                help_text="Complete streaming output from the agent during execution",
            ),
        ),
        migrations.CreateModel(
            name="TradingOperation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("OPEN_LONG", "Open Long"),
                            ("OPEN_SHORT", "Open Short"),
                            ("CLOSE_POSITION", "Close Position"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("ERROR", "Error"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="Base currency symbol (e.g., BTC)", max_length=20
                    ),
                ),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("leverage", models.IntegerField(blank=True, null=True)),
                (
                    "entry_price",
                    models.FloatField(
                        blank=True,
                        help_text="Price at which the position was opened",
                        null=True,
                    ),
                ),
                ("stop_loss_price", models.FloatField(blank=True, null=True)),
                ("take_profit_price", models.FloatField(blank=True, null=True)),
                (
                    "main_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stop_loss_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "take_profit_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full response from Binance API",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "workflow_execution",
                    models.ForeignKey(
                        blank=True,
                        help_text="The workflow execution that triggered this operation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations",
                        to="tradings.tradingworkflowexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trading Operation",
                "verbose_name_plural": "Trading Operations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "operation_type"],
                        name="tradings_tr_created_7964c9_idx",
                    ),
                    models.Index(
                        fields=["currency", "status"],
                        name="tradings_tr_currenc_850b8e_idx",
                    ),
                ],
            },
        ),
    ]
