# Generated by Django 5.2.7 on 2025-12-01 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0004_add_system_prompt_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingworkflowexecution',
            name='execution_frequency_minutes',
        ),
    ]
